plugins:
  - jest
  - fp
env:
  es2021: true
  node: true
  jest: true
extends:
  - airbnb-base
  - plugins:
      - jest
      - fp
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  no-console: 0
  import/extansions:
    - js: always
  no-underscore-dangle: [2, { "allow": ["_filename", "_dirname"] }]
  fp/no-nul: 0
  fp/no-unused-expression: 0
  fp/no-throw: 0
  fp/no-mutating-methods:
    - error
    - allowedObjects:
      - "_"
